"""
Unified Proposal Models for LLM-Driven RPG Engine.

This module defines structured proposal contracts for all LLM-driven operations.
Each proposal type represents a candidate output from the LLM that must be
validated before being committed to the canonical state.

Key principles:
- LLM outputs are proposals only; never mutate CanonicalState directly
- All proposals include audit metadata for traceability
- Every proposal has a deterministic fallback when LLM fails
- Proposals are parsed, repaired, validated, then accepted/rejected
"""

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import uuid4

from pydantic import BaseModel, Field

from .common import EntityReference


class ProposalType(str, Enum):
    """Types of proposals generated by LLM."""
    INPUT_INTENT = "input_intent"
    WORLD_TICK = "world_tick"
    SCENE_EVENT = "scene_event"
    NPC_ACTION = "npc_action"
    NARRATION = "narration"


class ProposalSource(str, Enum):
    """Source engine that generated the proposal."""
    INPUT_ENGINE = "input_engine"
    WORLD_ENGINE = "world_engine"
    SCENE_ENGINE = "scene_engine"
    NPC_ENGINE = "npc_engine"
    NARRATION_ENGINE = "narration_engine"


class RepairStatus(str, Enum):
    """Status of JSON repair attempt."""
    NONE = "none"  # No repair needed
    SUCCESS = "success"  # Repair succeeded
    FAILED = "failed"  # Repair failed, used fallback
    FALLBACK = "fallback"  # Used fallback directly


class ValidationStatus(str, Enum):
    """Status of proposal validation."""
    PENDING = "pending"  # Not yet validated
    PASSED = "passed"  # Passed all checks
    FAILED = "failed"  # Failed validation
    WARNING = "warning"  # Passed with warnings


class ProposalAuditMetadata(BaseModel):
    """Audit metadata attached to every proposal."""
    proposal_id: str = Field(default_factory=lambda: str(uuid4()), description="提案唯一标识符")
    proposal_type: ProposalType = Field(..., description="提案类型")
    source_engine: ProposalSource = Field(..., description="来源引擎")
    
    # Timing
    created_at: datetime = Field(default_factory=datetime.now, description="创建时间")
    latency_ms: int = Field(default=0, description="LLM调用延迟(毫秒)")
    
    # LLM call info
    prompt_template_id: Optional[str] = Field(None, description="使用的提示模板ID")
    model_name: Optional[str] = Field(None, description="使用的模型名称")
    input_tokens: int = Field(default=0, description="输入token数")
    output_tokens: int = Field(default=0, description="输出token数")
    
    # Raw output reference (truncated for storage)
    raw_output_preview: str = Field(default="", description="原始输出预览(前200字符)")
    
    # Repair trace
    repair_status: RepairStatus = Field(default=RepairStatus.NONE, description="修复状态")
    repair_attempts: int = Field(default=0, description="修复尝试次数")
    repair_strategies_tried: List[str] = Field(default_factory=list, description="尝试的修复策略")
    
    # Validation
    validation_status: ValidationStatus = Field(default=ValidationStatus.PENDING, description="验证状态")
    validation_errors: List[str] = Field(default_factory=list, description="验证错误列表")
    validation_warnings: List[str] = Field(default_factory=list, description="验证警告列表")
    
    # Fallback
    fallback_used: bool = Field(default=False, description="是否使用了回退")
    fallback_reason: Optional[str] = Field(None, description="回退原因")


class CandidateEvent(BaseModel):
    """A candidate event proposed by the LLM."""
    event_type: str = Field(..., description="事件类型")
    description: str = Field(..., description="事件描述")
    target_entity_ids: List[str] = Field(default_factory=list, description="目标实体ID列表")
    effects: Dict[str, Any] = Field(default_factory=dict, description="效果字典")
    importance: float = Field(default=0.5, ge=0.0, le=1.0, description="重要度")
    visibility: str = Field(default="player_visible", description="可见性(player_visible/hidden/gm_only)")


class StateDeltaCandidate(BaseModel):
    """A candidate state change proposed by the LLM."""
    path: str = Field(..., description="状态路径(如: npc_states.npc_001.mood)")
    operation: str = Field(default="set", description="操作类型(set/add/remove/increment)")
    value: Any = Field(..., description="新值")
    reason: str = Field(default="", description="变化原因")


class InputIntentProposal(BaseModel):
    """
    Proposal for parsing player natural language input into structured intent.
    
    Generated by: InputEngine
    Consumed by: ActionScheduler, ValidationLayer
    """
    # Core intent data
    intent_type: str = Field(..., description="意图类型(move/talk/attack/inspect/interact/idle/unknown)")
    target: Optional[str] = Field(None, description="目标对象ID或名称")
    target_type: Optional[str] = Field(None, description="目标类型(npc/location/item)")
    parameters: Dict[str, Any] = Field(default_factory=dict, description="额外参数")
    
    # Risk and context
    risk_level: str = Field(default="low", description="风险等级(low/medium/high)")
    raw_tokens: List[str] = Field(default_factory=list, description="原始分词结果")
    confidence: float = Field(default=0.5, ge=0.0, le=1.0, description="置信度")
    
    # Entity references
    mentioned_entities: List[EntityReference] = Field(default_factory=list, description="提及的实体")
    
    # Visibility (always player_visible for input intent)
    visibility: str = Field(default="player_visible", description="可见性")
    
    # Audit metadata
    audit: ProposalAuditMetadata = Field(..., description="审计元数据")
    
    # Fallback flag
    is_fallback: bool = Field(default=False, description="是否为回退结果")


class WorldTickProposal(BaseModel):
    """
    Proposal for world state changes and offscreen events.
    
    Generated by: WorldEngine
    Consumed by: ActionScheduler, ValidationLayer
    
    Handles:
    - Time progression
    - Offscreen NPC activities
    - Global state changes
    - Background events
    """
    # Time progression
    time_delta_turns: int = Field(default=1, description="时间推进回合数")
    time_description: str = Field(default="", description="时间推进描述")
    
    # Candidate events (offscreen)
    candidate_events: List[CandidateEvent] = Field(default_factory=list, description="候选事件列表")
    
    # State delta candidates
    state_deltas: List[StateDeltaCandidate] = Field(default_factory=list, description="状态变化候选")
    
    # Entity references (entities affected by this tick)
    affected_entities: List[EntityReference] = Field(default_factory=list, description="受影响实体")
    
    # Visibility
    visibility: str = Field(default="mixed", description="可见性(mixed/hidden/player_visible)")
    
    # Confidence
    confidence: float = Field(default=0.5, ge=0.0, le=1.0, description="置信度")
    
    # Audit metadata
    audit: ProposalAuditMetadata = Field(..., description="审计元数据")
    
    # Fallback flag
    is_fallback: bool = Field(default=False, description="是否为回退结果")


class SceneEventProposal(BaseModel):
    """
    Proposal for scene-specific content and interactions.
    
    Generated by: SceneEngine
    Consumed by: ActionScheduler, ValidationLayer
    
    Handles:
    - Scene-specific events
    - Environmental changes
    - Scene transitions
    - Discoverable content
    """
    # Scene context
    scene_id: str = Field(..., description="场景ID")
    scene_name: Optional[str] = Field(None, description="场景名称")
    
    # Candidate events (scene-specific)
    candidate_events: List[CandidateEvent] = Field(default_factory=list, description="候选事件列表")
    
    # State delta candidates
    state_deltas: List[StateDeltaCandidate] = Field(default_factory=list, description="状态变化候选")
    
    # Entity references
    affected_entities: List[EntityReference] = Field(default_factory=list, description="受影响实体")
    
    # Scene transition
    suggested_transition: Optional[str] = Field(None, description="建议的场景转换")
    transition_reason: Optional[str] = Field(None, description="转换原因")
    
    # Recommended actions (optional hints for player)
    recommended_actions: List[str] = Field(default_factory=list, description="推荐行动")
    
    # Visibility
    visibility: str = Field(default="player_visible", description="可见性")
    
    # Confidence
    confidence: float = Field(default=0.5, ge=0.0, le=1.0, description="置信度")
    
    # Audit metadata
    audit: ProposalAuditMetadata = Field(..., description="审计元数据")
    
    # Fallback flag
    is_fallback: bool = Field(default=False, description="是否为回退结果")


class NPCActionProposal(BaseModel):
    """
    Proposal for NPC actions based on context and memory.
    
    Generated by: NPCEngine
    Consumed by: ActionScheduler, ValidationLayer
    
    Handles:
    - NPC decisions
    - NPC actions
    - NPC dialogue
    - NPC state changes
    """
    # NPC context
    npc_id: str = Field(..., description="NPC ID")
    npc_name: Optional[str] = Field(None, description="NPC名称")
    
    # Action data
    action_type: str = Field(..., description="行动类型(observe/talk/act/move/idle)")
    target: Optional[str] = Field(None, description="目标实体ID")
    summary: str = Field(..., description="行动摘要")
    
    # Motivation
    visible_motivation: str = Field(default="", description="可见动机")
    hidden_motivation: Optional[str] = Field(None, description="隐藏动机(玩家不可见)")
    
    # State delta candidates
    state_deltas: List[StateDeltaCandidate] = Field(default_factory=list, description="状态变化候选")
    
    # Entity references
    affected_entities: List[EntityReference] = Field(default_factory=list, description="受影响实体")
    
    # Visibility
    visibility: str = Field(default="player_visible", description="可见性")
    
    # Confidence
    confidence: float = Field(default=0.5, ge=0.0, le=1.0, description="置信度")
    
    # Alternatives considered
    alternatives: List[str] = Field(default_factory=list, description="考虑过的备选方案")
    
    # Audit metadata
    audit: ProposalAuditMetadata = Field(..., description="审计元数据")
    
    # Fallback flag
    is_fallback: bool = Field(default=False, description="是否为回退结果")


class NarrationProposal(BaseModel):
    """
    Proposal for narrative text based on committed facts.
    
    Generated by: NarrationEngine
    Consumed by: TurnTransaction (for output)
    
    Key constraint: Narration cannot invent uncommitted facts.
    Must only describe what has been committed to canonical state.
    """
    # Narration content
    text: str = Field(..., description="叙事文本")
    
    # Style and tone
    tone: str = Field(default="neutral", description="语调(neutral/tense/peaceful/dramatic)")
    style_tags: List[str] = Field(default_factory=list, description="文风标签")
    
    # Context used (for audit)
    visible_context_id: Optional[str] = Field(None, description="使用的可见上下文ID")
    committed_facts_used: List[str] = Field(default_factory=list, description="使用的已提交事实ID")
    
    # Safety checks
    hidden_info_check_passed: bool = Field(default=True, description="隐藏信息检查是否通过")
    forbidden_info_detected: List[str] = Field(default_factory=list, description="检测到的禁止信息")
    
    # Entity references (entities mentioned in narration)
    mentioned_entities: List[EntityReference] = Field(default_factory=list, description="提及的实体")
    
    # Visibility (always player_visible for narration)
    visibility: str = Field(default="player_visible", description="可见性")
    
    # Confidence
    confidence: float = Field(default=0.5, ge=0.0, le=1.0, description="置信度")
    
    # Recommended actions (optional hints for player)
    recommended_actions: List[str] = Field(default_factory=list, description="推荐行动")
    
    # Audit metadata
    audit: ProposalAuditMetadata = Field(..., description="审计元数据")
    
    # Fallback flag
    is_fallback: bool = Field(default=False, description="是否为回退结果")


# Union type for all proposals
AnyProposal = InputIntentProposal | WorldTickProposal | SceneEventProposal | NPCActionProposal | NarrationProposal


# Fallback factory functions
def create_fallback_input_intent(
    raw_input: str,
    reason: str = "LLM call failed"
) -> InputIntentProposal:
    """Create a fallback InputIntentProposal when LLM fails."""
    return InputIntentProposal(
        intent_type="unknown",
        target=None,
        risk_level="low",
        raw_tokens=raw_input.split()[:10],
        confidence=0.0,
        mentioned_entities=[],
        audit=ProposalAuditMetadata(
            proposal_type=ProposalType.INPUT_INTENT,
            source_engine=ProposalSource.INPUT_ENGINE,
            fallback_used=True,
            fallback_reason=reason,
            validation_status=ValidationStatus.PASSED,
        ),
        is_fallback=True,
    )


def create_fallback_world_tick(
    reason: str = "LLM call failed"
) -> WorldTickProposal:
    """Create a fallback WorldTickProposal when LLM fails."""
    return WorldTickProposal(
        time_delta_turns=1,
        time_description="时间缓缓流逝...",
        candidate_events=[],
        state_deltas=[],
        affected_entities=[],
        confidence=0.0,
        audit=ProposalAuditMetadata(
            proposal_type=ProposalType.WORLD_TICK,
            source_engine=ProposalSource.WORLD_ENGINE,
            fallback_used=True,
            fallback_reason=reason,
            validation_status=ValidationStatus.PASSED,
        ),
        is_fallback=True,
    )


def create_fallback_scene_event(
    scene_id: str,
    reason: str = "LLM call failed"
) -> SceneEventProposal:
    """Create a fallback SceneEventProposal when LLM fails."""
    return SceneEventProposal(
        scene_id=scene_id,
        candidate_events=[],
        state_deltas=[],
        affected_entities=[],
        confidence=0.0,
        audit=ProposalAuditMetadata(
            proposal_type=ProposalType.SCENE_EVENT,
            source_engine=ProposalSource.SCENE_ENGINE,
            fallback_used=True,
            fallback_reason=reason,
            validation_status=ValidationStatus.PASSED,
        ),
        is_fallback=True,
    )


def create_fallback_npc_action(
    npc_id: str,
    reason: str = "LLM call failed"
) -> NPCActionProposal:
    """Create a fallback NPCActionProposal when LLM fails."""
    return NPCActionProposal(
        npc_id=npc_id,
        action_type="idle",
        summary="NPC静静地观察着周围。",
        confidence=0.0,
        audit=ProposalAuditMetadata(
            proposal_type=ProposalType.NPC_ACTION,
            source_engine=ProposalSource.NPC_ENGINE,
            fallback_used=True,
            fallback_reason=reason,
            validation_status=ValidationStatus.PASSED,
        ),
        is_fallback=True,
    )


def create_fallback_narration(
    reason: str = "LLM call failed"
) -> NarrationProposal:
    """Create a fallback NarrationProposal when LLM fails."""
    return NarrationProposal(
        text="场景在你眼前展开...",
        tone="neutral",
        confidence=0.0,
        audit=ProposalAuditMetadata(
            proposal_type=ProposalType.NARRATION,
            source_engine=ProposalSource.NARRATION_ENGINE,
            fallback_used=True,
            fallback_reason=reason,
            validation_status=ValidationStatus.PASSED,
        ),
        is_fallback=True,
    )
