"""add request_payload response_payload to model_call_logs

Revision ID: 629a7f8e996b
Revises: 005
Create Date: 2026-05-07 22:35:46.581112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '629a7f8e996b'
down_revision: Union[str, Sequence[str], None] = '005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'combat_sessions', 'event_logs', ['trigger_event_id'], ['id'])
    op.drop_index(op.f('uq_event_logs_session_turn_type'), table_name='event_logs')
    op.create_unique_constraint('uq_event_logs_session_turn_type', 'event_logs', ['session_id', 'turn_no', 'event_type'])
    op.create_foreign_key(None, 'event_templates', 'worlds', ['world_id'], ['id'])
    op.create_foreign_key(None, 'memory_facts', 'event_logs', ['source_event_id'], ['id'])
    op.add_column('model_call_logs', sa.Column('request_payload', sa.JSON(), nullable=True))
    op.add_column('model_call_logs', sa.Column('response_payload', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_call_logs', 'response_payload')
    op.drop_column('model_call_logs', 'request_payload')
    op.drop_constraint(None, 'memory_facts', type_='foreignkey')
    op.drop_constraint(None, 'event_templates', type_='foreignkey')
    op.drop_constraint('uq_event_logs_session_turn_type', 'event_logs', type_='unique')
    op.create_index(op.f('uq_event_logs_session_turn_type'), 'event_logs', ['session_id', 'turn_no', 'event_type'], unique=True)
    op.drop_constraint(None, 'combat_sessions', type_='foreignkey')
    # ### end Alembic commands ###
